[build]
  publish = "dist/"
  command = "npm run build"
  environment = { NODE_VERSION = "16" }

  [build.processing]
    skip_processing = false
  [build.processing.images]
    compress = true

[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
    paths = ["dist", ".cache"]

[[edge_functions]]
  path = "/"
  function = "easteregg"
